name: Release Beta Version

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  tag-beta-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Important: ensures all tags are fetched

    - name: Bump version and tag
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      run: |
        # Fetch tags
        git fetch --tags
        
        # Check if there are any tags in the repo
        if git rev-list --tags --max-count=1 | xargs git describe --tags --abbrev=0 > /dev/null 2>&1; then
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $LATEST_TAG"
          BASE_VERSION=${LATEST_TAG%-beta} # Remove -beta suffix if present
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)
          let PATCH+=1 # Increment patch version
        else
          echo "No tags found. Setting default version."
          MAJOR=0
          MINOR=1
          PATCH=0
        fi
        
        NEW_VERSION="$MAJOR.$MINOR.$PATCH-beta"
        echo "New version: $NEW_VERSION"
        
        # Configure git with your identity
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # Create and push new tag
        git tag -a $NEW_VERSION -m "Beta release $NEW_VERSION"
        
        # Use the PAT for authentication
        git push https://${{ secrets.MY_GITHUB_PAT }}@github.com/${GITHUB_REPOSITORY} --tags
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
