name: Release Version

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Important: ensures all tags are fetched

    - name: Bump version and tag
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      run: |
        # Fetch tags
        git fetch --tags
        
        # Check if there are any tags in the repo
        if git rev-list --tags --max-count=1 | xargs git describe --tags --abbrev=0 > /dev/null 2>&1; then
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $LATEST_TAG"
          
          # Assuming the tags follow semantic versioning without pre-release identifiers
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          let PATCH+=1 # Increment patch version
        else
          echo "No tags found. Setting initial version."
          MAJOR=0
          MINOR=0
          PATCH=1
        fi
        
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        
        # Configure git with your identity
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # Create and push new tag
        git tag -a "v$NEW_VERSION" -m "Release $NEW_VERSION"
        
        # Use the PAT for authentication
        git push https://${{ secrets.MY_GITHUB_PAT }}@github.com/${GITHUB_REPOSITORY} --tags
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
